# Generated by Django 5.0.1 on 2024-01-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=10)),
                ('flip_time', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Couter',
        ),
    ]
