# Generated by Django 5.0.1 on 2024-01-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two_app', '0002_counter_delete_couter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='flip_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
