# Generated by Django 5.0.1 on 2024-01-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two_app', '0004_author_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='birthday',
            field=models.DateField(),
        ),
    ]
